name: Action.NET for PriorityQueue
on:
  push:
    branches: [ master, PriorityQueue ]
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: set up
      uses: actions/setup-dotnet@v1
      with:
          dotnet-version: '6.0'
          
    - name: dotnet check
      run:  dotnet --version
    - name: Restore
      run: nuget restore PriorityQueue/PriorotyQueue/PriorotyQueue.sln
    - name: building
      run: dotnet build PriorityQueue/PriorotyQueue/PriorotyQueue.sln
    - name: test
      run: dotnet test PriorityQueue/PriorotyQueue/PriorotyQueue.sln
