# This is a basic workflow to help you get started with Actions

name: github_actions_basics_for_.NET

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
    
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: set up
      uses: actions/setup-dotnet@v1
      with:
          dotnet-version: '5.0'
     # check for dotnet
    - name: dotnet check
      run:  dotnet --version
    - name: Move1
      run: dir
    - name: Move2
      run: cd HomeTask1
    - name: Move3
      run: dir
    - name: Restore
      run: nuget restore MatrixMultiplication.sln
    - name: building
      run: dotnet build MatrixMultiplication.sln
    - name: test
      run: dotnet test MatrixMultiplication.sln
