# This is a basic workflow to help you get started with Actions

name: github_actions_basics_for_.NET

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, hometask5 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
    
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: set up
      uses: actions/setup-dotnet@v1
      with:
          dotnet-version: '5.0'
     # check for dotnet
    - name: dotnet check
      run:  dotnet --version
    #- name: DIR
    #  run: dir
    - name: Restore
      run: nuget restore HomeTask5/MyNunit/MyNUnit.sln
    - name: Restore TestClass1
      run: nuget restore HomeTask5/Testdata/Test1/Test1/Test1.sln
    - name: Restore TestClass2
      run: nuget restore HomeTask5/Testdata/Test2/Test2/Test2.sln
    - name: Restore TestClass3
      run: nuget restore HomeTask5/Testdata/Test3/Test3/Test3.sln
    
    - name: building
      run: dotnet build HomeTask5/MyNunit/MyNUnit.sln
    - name: building TestClass1
      run: dotnet build HomeTask5/Testdata/Test1/Test1/Test1.sln
    - name: building TestClass2
      run: dotnet build HomeTask5/Testdata/Test2/Test2/Test2.sln
    - name: building TestClass3
      run: dotnet build HomeTask5/Testdata/Test3/Test3/Test3.sln
    - name: test
      run: dotnet test HomeTask5/MyNunit/MyNUnit.sln
